version: '3'

services:
  app:
    image: samdevelopment/laraduck:1
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    ports:
      - 8080:80
    networks:
      - nicknet

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=henk
      - MYSQL_PASSWORD=secret
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 33060:3306
    networks:
      - nicknet

volumes:
  mysqldata:
    driver: local

networks:
  nicknet:
    driver: bridge